=== InfinitumFramework/Infinitum-Core/assets/infinitum-configuration-1.0.dtd
<!--
 Copyright (c) 2012 Tyler Treat
 
 This file is part of Infinitum Framework.

 Infinitum Framework is free software: you can redistribute it and/or modify
 it under the terms of the GNU Lesser General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Infinitum Framework is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Lesser General Public License for more details.

 You should have received a copy of the GNU Lesser General Public License
 along with Infinitum Framework.  If not, see <http://www.gnu.org/licenses/>. 
 
 <!DOCTYPE infinitum-configuration PUBLIC
	"-//Infinitum/Infinitum Configuration DTD 1.0//EN"
	"http://www.clarionmedia.com/infinitum/dtd/infinitum-configuration-1.0.dtd">
 
-->

<!ELEMENT infinitum-configuration (application? , sqlite? , rest? , domain? , beans?)>

<!ELEMENT application (property*)>
<!ELEMENT sqlite (property+)>
<!ELEMENT domain (model*)>
<!ELEMENT beans (component-scan , bean* , aspect*)>
<!ELEMENT rest (property+ , authentication?)>
<!ATTLIST rest ref CDATA #IMPLIED>

<!ELEMENT property (#PCDATA)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property ref CDATA #IMPLIED>
<!ATTLIST property value CDATA #IMPLIED>

<!ELEMENT model (#PCDATA)>
<!ATTLIST model resource CDATA #REQUIRED>

<!ELEMENT bean (property*)>
<!ATTLIST bean id CDATA #REQUIRED>
<!ATTLIST bean src CDATA #REQUIRED>
<!ATTLIST bean scope CDATA #IMPLIED>

<!ELEMENT aspect (property* , advice*)>
<!ATTLIST aspect id CDATA #REQUIRED>
<!ATTLIST aspect src CDATA #REQUIRED>
<!ATTLIST aspect scope CDATA #IMPLIED>

<!ELEMENT advice (#PCDATA)>
<!ATTLIST advice id CDATA #REQUIRED>
<!ATTLIST advice type CDATA #REQUIRED>
<!ATTLIST advice pointcut CDATA #REQUIRED>
<!ATTLIST advice value CDATA #REQUIRED>
<!ATTLIST advice order CDATA #IMPLIED>

<!ELEMENT component-scan (#PCDATA)>
<!ATTLIST component-scan enabled CDATA #IMPLIED>
<!ATTLIST component-scan base-package CDATA #IMPLIED>

<!ELEMENT resource (#PCDATA)>
<!ATTLIST resource name CDATA #REQUIRED>

<!ELEMENT authentication (property*)>
<!ATTLIST authentication strategy CDATA #IMPLIED>
<!ATTLIST authentication ref CDATA #IMPLIED>
<!ATTLIST authentication enabled CDATA #IMPLIED>
<!ATTLIST authentication generator CDATA #IMPLIED>
<!ATTLIST authentication header CDATA #IMPLIED>

=== InfinitumFramework/Infinitum-Core/src/test/resources/infinitum.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (C) 2013 Clarion Media, LLC
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE infinitum-configuration PUBLIC
    "-//Infinitum/Infinitum Configuration DTD 1.0//EN"
    "http://clarionmedia.com/infinitum/dtd/infinitum-configuration-1.0.dtd">

<infinitum-configuration>

    <application>
        <property name="debug">true</property>
        <property name="mode">annotations</property>
        <property name="recycleCache">true</property>
        <property name="methodCaching">true</property>
    </application>

    <sqlite>
        <property name="dbName">test</property>
        <property name="dbVersion">1</property>
        <property name="generateSchema">true</property>
        <property name="autocommit">true</property>
    </sqlite>

    <rest>
        <property name="messageType">json</property>
        <property name="host">http://localhost/test</property>
        <authentication strategy="token" header="true" enabled="true">
            <property name="tokenName">token</property>
            <property name="token">e489e8383c0ae2b7fe4dcf178330b4ac</property>
        </authentication>
    </rest>

    <domain>
        <model resource="com.clarionmedia.infinitum.Foo"/>
        <model resource="com.clarionmedia.infinitum.Bar"/>
    </domain>

    <beans>
        <component-scan base-package="com.clarionmedia.infinitum"/>
        <bean id="baz" src="com.clarionmedia.infinitum.Baz"/>
        <aspect id="qux" src="com.clarionmedia.infinitum.Qux"/>
    </beans>

</infinitum-configuration>
